### ISSUE TITLE
Usage of blocks as "Expires In" unit is confusing

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/electrum-nmc#101]
The "Expires In" column in the [Manage Names tab](https://github.com/namecoin/namecoin.org/blob/master/images/screenshots/electrum-nmc/2018-10-06-Manage-Names-Tab.png) uses blocks as the unit of time.  This is confusing to novice users; see https://twitter.com/SendRVNtoWOKE/status/1096559487497003009 for an example.

**Comment by samurai321** [comment]
Should be in days, hours and minutes. And just plain display "expired" after it expired.

**Comment by JeremyRand** [comment]
It needs to be made clear that any days/hours/minutes measurement shown is an estimate, and that users shouldn't assume that they'll be able to renew if they wait until, say, 30 minutes before the shown date/time.

**Comment by samurai321** [comment]
> 
> 
> It needs to be made clear that any days/hours/minutes measurement shown is an estimate, and that users shouldn't assume that they'll be able to renew if they wait until, say, 30 minutes before the shown date/time.

Maybe just show days/hours. 

Less than an hour and just show "About to expire" or similar.

When you hover the field, it can show you the blocks remaining.
