### ISSUE TITLE
About section does not list Jeremy Rand as a developer

### ISSUE THREAD

**Issue by somewhatnmc** [namecoin/electrum-nmc#142]
<>

**Comment by JeremyRand** [comment]
This is specific to the Android GUI, correct?

**Comment by somewhatnmc** [comment]
Unsure at this point as have removed earlier versions of electrum-nmc from machine at hand and am having issue running/installing 3.3.6 on Windows 10(#143).

**Comment by somewhatnmc** [comment]
This is apk specific, although probably shouldn't be.
