### ISSUE TITLE
run_electrum_nmc not included in Windows binary?

### ISSUE THREAD

**Issue by somewhatnmc** [namecoin/electrum-nmc#143]
Receiving a fatal error on Windows 10. The run_electrum_nmc script does not appear to be included.

**Comment by somewhatnmc** [comment]
Same issue using the installer, can't find the run_electrum_nmc file in folder.

**Comment by JeremyRand** [comment]
Can you post the exact text and a screenshot of the error you're getting?

**Comment by JeremyRand** [comment]
I did an initial look-through of the Windows build code and I don't see anything that would be likely to cause this symptom; a screenshot and exact text would be helpful in tracking down the bug.

**Comment by somewhatnmc** [comment]
![runElectrum](https://user-images.githubusercontent.com/49384990/58134484-7d9bd480-7c16-11e9-8cbd-92981ef714bf.png)

**Comment by somewhatnmc** [comment]
Traceback (most recent call last):
  File "run_electrum_nmc", line 359, in <module>
  File "electrum_nmc\daemon.py", line 348, in init_gui
ModuleNotFoundError: No module named 'electrum_nmc.gui.qt'

**Comment by JeremyRand** [comment]
Hmm, with the installer version, can you provide a screenshot of the contents of the directory you installed it to?  (The directory that has the `electrum_nmc` and `contrib` subdirectories in it.)

**Comment by JeremyRand** [comment]
Ah, hmm, I'm looking at the line that the traceback mentions.  It's definitely a piece of code that I fiddled with recently.  Is there a file called `daemon.py` anywhere in the installation folder (using the installer)?  If so, can you look at line 348 of it, and try changing the `electrum_nmc` on that line to `electrum`?  There are two instances of it on that line; try changing each one individually, and also try changing them both, and let me know which sets of changes make a difference (if any do).

**Comment by somewhatnmc** [comment]
I can't find daemon.py unfortunately.

**Comment by JeremyRand** [comment]
I can reproduce the dialog in the screenshot on my Windows machine.  What exactly did you do to produce the traceback that you pasted?

**Comment by somewhatnmc** [comment]
![dir](https://user-images.githubusercontent.com/49384990/58138915-f0fa1200-7c27-11e9-94c7-dd47bfb865db.png)

**Comment by JeremyRand** [comment]
Interestingly, the Python zip works fine on Windows, so I assume there's an issue with the .exe packaging scripts somewhere.  Not sure exactly where though.

**Comment by somewhatnmc** [comment]
(this is where it gets annoying for you i think )using bash ./electrum-nmc-nc3.3.6.exe

**Comment by JeremyRand** [comment]
hmm, I wonder if the PE header trick I used for certutil will be able to approximate the behavior you're achieving via bash....

**Comment by somewhatnmc** [comment]
For context, I had used 3.3.3.1.1.(1) on this machine with no issue.

**Comment by somewhatnmc** [comment]
I am *somewhat* indisposed so may take time to respond. Apologies.

**Comment by JeremyRand** [comment]
Well, I figured out how to extract a PyInstaller exe file, and I definitely see something wrong.  Electrum-NMC's exe file doesn't have any of the Python modules for the `electrum_nmc.gui` package, whereas upstream Electrum (same version) does have them.  I have no idea why exactly they're missing though.  This certainly explains the traceback you got.

**Comment by JeremyRand** [comment]
I have a lead, but it's not a very likely one.  Will hopefully have more info on whether that lead has panned out in circa 30 minutes.

**Comment by JeremyRand** [comment]
Pursuing another couple of leads...

**Comment by JeremyRand** [comment]
Relatively sure I see what's wrong.  Fix will hopefully be out tomorrow.
