### ISSUE TITLE
Auxpow deserialisation is hackish

### ISSUE THREAD

**Issue by domob1812** [namecoin/electrum-nmc#154]
When deserialising an auxpow, we [call back](https://github.com/namecoin/electrum-nmc/blob/7cbe2a3753abca358a667388d4109451e3f5de0a/electrum/auxpow.py#L127) to `blockchain.deserialize_header` for the parent header.  This must then only parse a header *without auxpow*.  That's the case because `1` is passed as faked block height, and at that height auxpow is disabled in Namecoin.

That is however quite a hack.  That subtle behaviour (and the meaning of the magic number) is not explained in a comment in the code, and this implicitly assumes that auxpow actually starts at a block later than one.  While true for Namecoin, this is not true for general auxpow chains (for which the `auxpow` branch is meant).

A cleaner solution would be doing what we do in Bitcoin Core:  We can have a separate function for deserialising a plain block header without auxpow, and then call that from the auxpow deserialisation as well as from the "real" block-header deserialiser.

**Comment by domob1812** [comment]
@JeremyRand, would you object if I create a patch that changes the code as suggested?

**Comment by domob1812** [comment]
Also related to this:  When [deserialising a header read from disk](https://github.com/namecoin/electrum-nmc/blob/0be7672191cc8345ac7856e8d69c66f8f72a5154/electrum_nmc/electrum/blockchain.py#L499), we should presumably also do just the base deserialisation without auxpow (since auxpow's get stripped for the on-disk headers).

Here again, the current code just works because auxpow deserialisation has a check at the beginning to gracefully handle EOF.  That seems like a hack to me, too - the calling code should know whether or not it expects an auxpow, and then we should actually fail if trying to deserialise one that is not there.

**Comment by JeremyRand** [comment]
Good points -- the current hacks are undesirable.  It's not clear to me that using a separate function is the best approach, as it might make merges from upstream more error-prone (will a change to the upstream `deserialize_header` reliably produce a merge conflict if there are 2 functions in our branch, or will maybe some upstream changes silently diverge our code from upstream?)  It seems to me that it would make more sense to add an optional argument `auxpow_active=True`, and set it to `False` in the specific cases where we don't want AuxPoW to be deserialized.

Thoughts?

**Comment by domob1812** [comment]
Adding a flag is actually what I did so far while playing around, but that just seems to make the code even messier.  IMHO a separate function is cleaner in code for the long run.

Since that new function would basically be what the upstream function is, it would effectively just be a rename.  Hence I don't think merge conflicts will be a big deal; we have some of these cases in Bitcoin Core as well, and there it never caused issues for me.

We could even rename the function that parses *with auxpow* to something like `blockchain.deserialize_header_with_auxpow` instead.  Then the "basic block header" function is unchanged compared to upstream, and the only change we do is adding another one that parses auxpow's in addition, and changing the places that need that to call this function instead of the "original one".

**Comment by domob1812** [comment]
The points mentioned above have been cleaned up now with #161.
