### ISSUE TITLE
"Insufficient funds" in Regtest functional tests 

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/electrum-nmc#178]
The Regtest functional tests are hanging after an "Insufficient funds" error, see https://travis-ci.org/namecoin/electrum-nmc/jobs/590695751#L384 .

**Comment by JeremyRand** [comment]
@domob1812 Do you by any chance see what's wrong here?  My understanding of the Namecoin Core part of these tests isn't really strong enough to see what's going wrong.

**Comment by domob1812** [comment]
One thing that comes to mind is the increased feerate of Namecoin.  So if the amounts in the test are chosen very tightly, it could be that Namecoin cannot find enough fees to attach.  That is just a vague guess, though.

Is it possible to see Namecoin Core's `debug.log` from the test?

**Comment by JeremyRand** [comment]
@domob1812 I've added a temporary patch in #181 to show `debug.log`; see anything interesting here?  https://travis-ci.org/namecoin/electrum-nmc/jobs/600329677

**Comment by domob1812** [comment]
@JeremyRand thanks - unfortunately there is nothing suspicious I can see in the output logs.  But if you would really run into the feerate issue, I'm not sure what you would see in debug.log.  Perhaps the next step would be tracing where exactly the error happens in the test and then printing the wallet balances right before.

**Comment by JeremyRand** [comment]
It is highly interesting that a user on our forum also recently reported an erroneous "Insufficient funds" error.  https://forum.namecoin.org/viewtopic.php?p=17690#p17690

I wonder if these have the same underlying cause.  Maybe something broken in the coin selection algorithm?
