### ISSUE TITLE
Impossible to register names! 

### ISSUE THREAD

**Issue by ghost** [namecoin/electrum-nmc#179]
![registration cleaned](https://user-images.githubusercontent.com/56533943/66734597-404d1300-ee53-11e9-839a-20b2fa5e2842.png)
Hello,

I find it absurd that the only meaningful way to register a Namecoin .bit address is using this Electrum fork. I tried to obtain a registration but is impossible. Just paying the fees and just paying the fees. If I right click on any empty space under "Manage Names" it will crash..

`Traceback (most recent call last):
  File "/electrum_nmc/electrum/gui/qt/uno_list.py", line 213, in create_menu
    copy_ascii = data.decode('ascii')
AttributeError: 'NoneType' object has no attribute 'decode'
 
Additional information
Electrum version: 3.3.7 
Python version: 3.7.5rc1 (default, Oct 8 2019, 16:47:45) [GCC 9.2.1 20190909] 
Operating system: Linux-5.2.0-xx-amd64-x86_64-with-debian-xx 
Wallet type: standard 
Locale: en_US `

Transactions confirmed and now I stucked. I have also a full Namecoin node installed but it is impossible to select which coin I want to spend for registration and so I stuck also with this software which is not working.

**Comment by JeremyRand** [comment]
Okay, so first off, your tone is inappropriate for a bug tracker, particularly given that Electrum-NMC is clearly labeled as beta software.

Second, I'm counting at least 3 different issues that you've combined into 1 post (registration not working, the `AttributeError` in the context menu, and a Namecoin Core issue that doesn't even belong in this repo).  Please don't combine issues, as it makes things unnecessarily complex to keep track of things.

I will assume that this issue will henceforth be dedicated to the `AttributeError` in the context menu.

Anyway, it looks like I can reproduce the error; I'll see if I can get a fix coded up shortly.
