### ISSUE TITLE
test_encode_decode_msg__ints_can_be_passed_as_bytes failing

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/electrum-nmc#262]
`test_encode_decode_msg__ints_can_be_passed_as_bytes` is failing, see [the trace on Travis](https://travis-ci.org/github/namecoin/electrum-nmc/jobs/705068752#L895-L916).

**Comment by JeremyRand** [comment]
@domob1812 I think you glanced at this earlier and said it looks like a rebranding error?  Is this likely to be due to the genesis block hash being different between Bitcoin and Namecoin?

**Comment by JeremyRand** [comment]
> Is this likely to be due to the genesis block hash being different between Bitcoin and Namecoin?

Yep, that was it.

**Comment by domob1812** [comment]
Yes exactly, thanks for the fix!
