### ISSUE TITLE
MemoryError('dropping message over 1,000,000 bytes and re-synchronizing',)

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/electrum-nmc#27]
The following error shows up in verbose mode during sync:

~~~
MemoryError('dropping message over 1,000,000 bytes and re-synchronizing',)
~~~

After this error, it stops syncing.  Error observed with Git hash e10497b2196f456620edbe2ed9fcb02fd425c3d9 .

**Comment by JeremyRand** [comment]
The error seems to originate from the `max_size=250 * 4000` default setting in the `aiorpcx` dependency.

**Comment by JeremyRand** [comment]
Adding a line at the end of `NotificationSession.__init__` like this:

~~~
self.framer.max_size = 2000000
~~~

Seems to be effective at raising the limit.  Just need to figure out what the correct limit is.  (It should be noted that it's expected for Namecoin to have larger header transfers than Bitcoin, because Namecoin's block headers have extra AuxPoW data that can be quite large.)

**Comment by JeremyRand** [comment]
A limit of 10000000 (10 MB) seems to work fine empirically.  Probably wise to bump it to 20 MB so that we have a bit of extra wiggle room.

**Comment by vincib** [comment]
Please note that if you have the same error on an electrum 4.0.3, you should change MAX_INCOMING_MSG_SIZE in electrum/interface.py instead.
