### ISSUE TITLE
Start electrum-NMC without wallet

### ISSUE THREAD

**Issue by rllola** [namecoin/electrum-nmc#287]
Is it possible to start electrum-NMC without a wallet configured in order to only collect .bit domain name ?

**Comment by JeremyRand** [comment]
I'm pretty sure Electrum-NMC doesn't load a wallet in daemon mode unless you explicitly tell it to.  In GUI mode, I suspect wallet loading is mandatory.

**Comment by rllola** [comment]
Yeah I found out after creating the issue. Closing.
