### ISSUE TITLE
Trezor shows different address than electrum-nmc

### ISSUE THREAD

**Issue by matso167** [namecoin/electrum-nmc#3]
On receive tab, when eye icon is clicked, Trezor shows different address on its screen than whats displayed in electrum-nmc.

electrum-nmc 3.1.3-beta1
MacOS
Trezor One

**Comment by JeremyRand** [comment]
> On receive tab, when eye icon is clicked, Trezor shows different address on its screen than whats displayed in electrum-nmc.

@matso167 Hi, thanks for the bug report.  Debugging this will be Fun (TM) since I don't have a Trezor available to test this, but I suspect that this issue is either due to an incorrect prefix, or an incorrect HD wallet chaincode.  Can you tell me whether the prefix is correct or incorrect on both the Trezor and in Electrum-NMC?  (If you're not sure how to check this, this can be approximated by telling me the first character of each address.)

Cheers!

**Comment by matso167** [comment]
Trezor displays "BTC Legacy Account" starting with 1 while electrum-nmc address starts with N.

**Comment by JeremyRand** [comment]
Thanks @matso167.  Do you happen to use any Bitcoin forks besides Namecoin with Electrum + your Trezor?  If so, can you point me to the source code of one of them?  I'd guess that it should be easy to diff the relevant areas of code to see what I missed.

**Comment by matso167** [comment]
Sorry cant help with source codes.

**Comment by JeremyRand** [comment]
@matso167 On a hunch, can you try changing the word "Bitcoin" to "Namecoin" in this line?  https://github.com/namecoin/electrum-nmc/blob/14d5d248e2bf17358bd9e7e84f9cf9596f422bd3/plugins/trezor/trezor.py#L177  That line looks suspiciously like a mechanism to tell the Trezor what chain is being used.

**Comment by JeremyRand** [comment]
Hmm.  I'll have to do some more digging; I'll see if I can track down the issue in the next few days.

**Comment by matso167** [comment]
I did some more digging. I'm not very familiar with python environment, so I dindn't know I had to run 
`pip3 install .[full]`
to activate changes in code.

Now when i changed that Bitcoin -> Namecoin, Trezor displays warning: "Wrong address path for selected coin. Continue at your own risk!"

Derivation path I'm using is:
m/44'/0'/0'

Not sure what derivation path is best supported on Namecoin.

After pressing Continue, I get same address as in electrum-nmc. Account name is still BTC legacy account.

**Comment by matso167** [comment]
m/49'/0'/0' and m/84'/0'/0' derivation paths give error "cant encode address".

**Comment by JeremyRand** [comment]
@matso167 Ah, excellent, that is progress.  Where are you changing the derivation path?  I'm not sure exactly where you are in the code.

On a hunch, can you try changing the 0 at the end of this line to 7 and tell me what happens?

https://github.com/namecoin/electrum-nmc/blob/989c9c2b55ed2acecb9b779753cbdc3a475e5758/lib/keystore.py#L712

Thanks for your help so far on this!

**Comment by JeremyRand** [comment]
> so I dindn't know I had to run
>     pip3 install .[full]

FWIW, I usually run `pip3 uninstall electrum-nmc` before I run the line you listed.  I don't know if it's actually necessary to trigger the update to take effect.

**Comment by matso167** [comment]
Derivation path is asked in UI :)

**Comment by matso167** [comment]
Yes addresses match.

**Comment by JeremyRand** [comment]
> Yes addresses match.

Great!  Thank you so much for helping debug this.  I'll commit the relevant changes to the Git repo when I have a few minutes (sometime before the next release).  Would you like me to credit you on the Namecoin.org news section when the fixes are released?  If so, what name should I credit you as?

**Comment by matso167** [comment]
Not necessary. Nice to get it working with Trezor :)

**Comment by curiosity81** [comment]
Hello,

this also works with a Trezor T. Both changes are necessary:

1. line 177 in electrum-nmc/plugins/trezor/trezor.py: Bitcoin to Namecoin
2. line 712 in electrum-nmc/lib/keystore.py: 0 to 7

Good work Jeremy.

**Comment by curiosity81** [comment]
FYI, I sent some namecoins to an address generated by the Trezor T today and the transaction was recognized by electrum-nmc. Tomorrow or so, I will test, whether I can spent those coins too.

**Comment by JeremyRand** [comment]
> However, I tried to sent the coins without fee. Electrum-nmc complained, that there were insufficient funds. So I pressed the max-button on the send pane, and it filled in some tiny fee. But I can see in the mempool, that there are also transactions without fee (https://bchain.info/NMC/). Maybe I used the software wrongly, since it was my second transaction with an electrum variant.

@curiosity81 I wouldn't be surprised if Electrum doesn't let you send zero-fee transactions, since those haven't been allowed on Bitcoin's network for many years.  (I have no idea why the Namecoin miners are willing to mine them; if I were mining Namecoin I'd be refusing to mine those.)  I don't see much point in trying to patch Electrum-NMC to change Electrum's behavior on this.

**Comment by curiosity81** [comment]
Did it work for you? Because of the failed build (#3) in "Make Trezor work with Namecoin" ...

I could test the current code if needed.
