### ISSUE TITLE
The Trezor functionality of the Electrum-NMC wallet is experiencing issues.

### ISSUE THREAD

**Issue by querydragon** [namecoin/electrum-nmc#357]
Electrum-NMC is the Electrum wallet for NAMECOIN.

You can obtain the latest version of this wallet for Namecoin at the following address: https://www.namecoin.org/download/betas/#electrum-nmc

Trezor device recognition in Electrum-NMC is working smoothly without any problems.

I have purchased several .bit domains from a different address and transferred them to the Electrum-NMC Trezor address, considering the enhanced security of Trezor.

The Electrum-NMC wallet supports the purchase, sale, and resetting of .bit domains for Namecoin.

Transferring Namecoin from the Electrum-NMC Trezor address to another address works seamlessly without any issues.

However, when attempting to purchase .bit domains with the Electrum-NMC Trezor address, trying to transfer .bit domain addresses imported from another wallet, attempting to change the settings of owned .bit domains, and in various similar scenarios, clicking the confirmation button on the Trezor device results in multiple error messages, and the transaction fails.

Please investigate and address this issue.

I have no control over the .bit domain addresses sent to the Trezor wallet address. It seems like the Electrum-NMC Trezor wallet is a graveyard for .bit domain addresses.

I attempted recovery using BIP39, treating it as a standard wallet in Electrum-NMC rather than a Trezor device. However, there is no way to access the Trezor Namecoin wallet address created as a hidden wallet, not as a standard wallet in the Trezor Suite.

Please help; this is a critical issue.

Thank you.

**Comment by JeremyRand** [comment]
Dup of https://github.com/namecoin/electrum-nmc/issues/121
